### ISSUE TITLE
Skill target on servant sometime click to the right of servant and miss skill (Pixel 6)

### ISSUE THREAD

**Issue by TeslasFoil** [Fate-Grand-Automata/FGA#1474] opened 2022-12-06 18:54 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1904

### Describe the bug

Happens on pixel 6, did not happen to pixel 4 (b1599), screen size 1080 x 2280

When a servant use skill that targets servant 2 (may happen on other servant position as well but have not seen it firsthand), the selection sometime occurs just to the right of servant portrait and misses skill
this happens quite often for me (20-30% of time)

### Video

could not record video, get Invalid media projection error when try to record screen

### Device model

Pixel 6

### Android version

12

### Screen size

1080x2400

### RAM

8gb

**Comment by xHomu** [comment] 2022-12-06 19:50
I have a Pixel 7 Pro and experiences this as well. @reconman has been [investigating this issue in recent weeks.](https://github.com/Fate-Grand-Automata/FGA/issues/1450#issuecomment-1335279749)

Watching the battles with debug mode on - I noticed that this occurs most often on repeats, which skips the face-card check for some reason.

**Comment by reconman** [comment] 2022-12-06 19:52
Duplicate of #1452

**Closed by reconman** 2022-12-06 19:52 UTC
Labels: bug
