### ISSUE TITLE
FGA plot skipping function cannot be executed

### ISSUE THREAD

**Issue by 2312946794** [Fate-Grand-Automata/FGA#1562] opened 2023-04-01 07:16 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1951

### Describe the bug

I have activated the skip episode feature of the program, but when I go to the episode page, the program stays unresponsive. The program play button is located at the bottom left. All other functions execute normally.

### Video

https://user-images.githubusercontent.com/55449372/229271503-0d0a3d22-cad3-4773-a9c4-c6181b81c6b6.mp4

### Device model

NOX  7.0.5.5

### Android version

9

### Screen size

1280*720

### RAM

4GB

**Comment by vybze** [comment] 2023-04-02 19:15
If I'm remembering correctly I believe that feature was disabled because it was causing with skills being used at the wrong time

**Comment by reconman** [comment] 2023-04-03 09:34
Duplicate of #1282

But I'll probably remove the feature instead. It's too unreliable.

**Closed** 2023-04-03 09:34 UTC
Labels: bug
