### ISSUE TITLE
Freezes in support list

### ISSUE THREAD

**Issue by ArashioX** [Fate-Grand-Automata/FGA#1171] opened 2022-05-01 06:42 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

1669

### Describe the bug

In support screens, fga stops and didnt do anything. Aldo, the support image maker dont show up when I try to presa play on support list. My vídeo ia from the inside built screen recorrer.

### Video

![Screenshot_2022-05-01-03-35-35-744_io rayshift betterfgo ep](https://user-images.githubusercontent.com/104710503/166135286-8d71150e-9af8-4473-9b7b-88dc52ca9b94.jpg)

### Device model

Poco F3

### Android version

12

### Screen size

2000x1080

### RAM

6gb

**Comment by reconman** [comment] 2022-05-01 06:44
That's a screenshot, not a video.

I need it for diagnosing your bug.

**Comment by ArashioX** [comment] 2022-05-01 06:49
Video: https://youtu.be/_UAXCP4t2f4
My Android is not rooted

**Comment by ArashioX** [comment] 2022-05-01 06:49
> That's a screenshot, not a video.
> 
> I need it for diagnosing your bug.

Sorry, the video was too big

**Comment by reconman** [comment] 2022-05-01 06:51
I also need debug rectangles.

**Comment by ArashioX** [comment] 2022-05-01 06:53
> I also need debug rectangles.

Ok, i'm uploading the New one

**Comment by ArashioX** [comment] 2022-05-01 06:58
> I also need debug rectangles.

https://youtu.be/_RS_Qtv9zlU

**Comment by reconman** [comment] 2022-05-01 07:09
Something is very wrong on your device. Did you change any fine tune settings?

**Comment by ArashioX** [comment] 2022-05-01 07:11
No, I didnt. I installed like the video shows me how to do.

**Comment by ArashioX** [comment] 2022-05-01 07:12
I use betterfgo, not the original app. My game plays in 60 dps. Maybe is that?

**Comment by ArashioX** [comment] 2022-05-01 07:13
The battle has no bugs, the only problem is on select support.

**Comment by reconman** [comment] 2022-05-01 20:48
Could be, the fast flashing rectangles are not normal.

**Comment by Crescent07891** [comment] 2022-06-17 19:49
I am also having this issue and I do not run BetterFGO

**Comment by reconman** [comment] 2022-06-17 19:54
It's not because of BetterFGO, I think the original issue is because of battery optimization.

@Crescent07891 Check the troubleshooting guide. If that doesn't help, open a new issue. I need a lot more information.

**Comment by darwinlinardi** [comment] 2022-07-06 06:16
I don't want to open another thread so while not the exact problem faced by OP, I have faced this problem of being stuck in the support selection screen several times in the past (Samsung Note 9), usually only reinstalling it works. I have tried the following which did not work:
- Restarting and force closing the app
- Restarting the phone
- Turning off servant card recognition
- Turn on debugging.

When I encountered the problem again, I found that selecting the support manually once would continue the loop as normal. It has been fine until now but if the bug persists will try this solution again to see if it will fix it. 
Video link: https://youtu.be/BtX57lLAyCU
To clarify, the scrolling down around 2:20 was done manually by me. At 4:40 the bug was not longer present and the scrolling by FGA works as intended.

Hopefully, this can help.

**Comment by reconman** [comment] 2022-07-06 06:44
@darwinlinardi Your play button was in the way at 2:20 but you moved it before 4:40.

Never place the play button inside of red rectangles.

That's why we tell people to put it into the bottom left.

**Comment by darwinlinardi** [comment] 2022-07-06 07:14
Thanks @reconman

**Comment by reconman** [comment] 2022-07-15 18:49
I'm closing this because the original author doesn't respond anymore.

**Closed by reconman** 2022-07-15 18:49 UTC
Labels: bug
