### ISSUE TITLE
Ability to auto-add friends after battle / specifically choose non friends?

### ISSUE THREAD

**Issue by Sabagabu** [Fate-Grand-Automata/FGA#1093] opened 2022-02-07 11:38 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hello, I'm looking to see if theres any option im missing to auto-add friends after battle? thanks. also, often times the tool clicks a skil by accident and wont close the prompt, is there something to do about it? many thanks!

**Comment by reconman** [comment] 2022-02-07 19:50
Duplicate of #977

**Closed by reconman** 2022-02-07 19:50 UTC
Labels: question

**Comment by Sabagabu** [comment] 2022-02-07 21:34
I'm moreso asking since the option exists as said in 977, where do i find it?

**Comment by reconman** [comment] 2022-02-07 21:35
977 is still an open feature request.
