### ISSUE TITLE
CN server UI has changed after update 

### ISSUE THREAD

**Issue by OXERIS** [Fate-Grand-Automata/FGA#862] opened 2021-09-07 12:41 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1488

### Describe the bug

the ui of cn server  has changed ,for the server has been updated today

### Video

add later

### Device model

Samsung s10+

### Android version

11

### Screen size

2280＊1080

### RAM

8GB

**Comment by reconman** [comment] 2021-09-07 12:42
Duplicate of #861

**Closed by reconman** 2021-09-07 12:42 UTC
Labels: bug
