### ISSUE TITLE
Unable to detect card type

### ISSUE THREAD

**Issue by Mizu0025** [Fate-Grand-Automata/FGA#958] opened 2021-11-16 23:09 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

FGA seems to be unable to detect the proper card type in battle, now that NA has updated to have widescreen support.

### Video

https://streamable.com/aslipd

### Device model

Pixel 4

### Android version

12

### Screen size

1080x2280

### RAM

6GB

**Comment by reconman** [comment] 2021-11-18 22:23
Does build 1557 help?

**Comment by reconman** [comment] 2021-11-18 22:50
I think it's because of your black bars on both sides which shouldn't be there. You'll need to find a way to change that in order to be able to use Servant detection.

In 1557 an option was added to ignore the face card detection but just hides your problem and doesn't solve it.

Also, another user with a Pixel 4a has completely different black bars where it also doesn't work: https://github.com/Fate-Grand-Automata/FGA/issues/964#issuecomment-972428213

**Comment by Mizu0025** [comment] 2021-11-19 10:26
> I think it's because of your black bars on both sides which shouldn't be there. You'll need to find a way to change that in order to be able to use Servant detection

Hm. I didn't notice any black bars during normal app play, but checking the video shows them; odd. After swapping to 3-symbol navigation from gesture nav, the script automation works in general now, but the 'fail to recognise card' issue remains; both with & without ignore notch enabled. No black bars in the video script either, that I can see?
https://streamable.com/kq4jxj

**Comment by reconman** [comment] 2021-11-19 11:17
Well, now it's better. Servant detection still seems to have a problem with detecting Chen Gong, so it's currently not implemented perfectly.

**Comment by SeraphSephiroth** [comment] 2021-11-21 11:49
on my phone it's about the orientation. It works with the screen rotated one way, but I get the error if I rotate my phone

**Comment by CDB-Man** [comment] 2021-11-21 17:21
![Screenshot_20211121-121613_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/14037303/142772237-dad6f1bf-d577-43d5-95e6-137950ec4f35.jpg)
In my case, you can see it fails to recognize card 4 on wave 3, which is when I max buff Yagyu.  I suspect maybe it's due to the # of buff icons on his card? It doesn't complain about Yagyu on wave 2 when he has no buffs.  In the prior canary release before the widescreen update, it had no issues with Yagyu having this many buffs.

**Comment by CDB-Man** [comment] 2021-11-24 03:05
If the buff icons are a contributing factor, perhaps ignore the top 20 pixels so that top row doesn't contribute?  Just an idea!

**Comment by SeraphSephiroth** [comment] 2021-11-24 12:43
> 

If you flip your device to the other side does it still show the error?

**Comment by SeraphSephiroth** [comment] 2021-11-24 12:44
> If the buff icons are a contributing factor, perhaps ignore the top 20 pixels so that top row doesn't contribute? Just an idea!

If you flip your device to the other side does it still show the error?

**Comment by CDB-Man** [comment] 2021-11-24 13:43
> > If the buff icons are a contributing factor, perhaps ignore the top 20 pixels so that top row doesn't contribute? Just an idea!
> 
> If you flip your device to the other side does it still show the error?

Confirmed the issue appears on both orientations (left edge on the bottom, right edge on the bottom).

**Comment by DNLMow** [comment] 2021-11-30 02:35
https://github.com/Fate-Grand-Automata/FGA/issues/920
Seems similar.

**Comment by TrueSalmonKing** [comment] 2021-12-23 14:34
Don't know if it'll help others with different devices but I was able to avoid this issue by setting min similarity value to 70 _in more options -> advanced -> fine-tune_

Device: Xiaomi Redmi Note 9 Pro

**Comment by reconman** [comment] 2021-12-23 15:06
Most issues are related to black bars or were already fixed with the last release, closing.

**Closed by reconman** 2021-12-23 15:06 UTC
Labels: bug
