### ISSUE TITLE
Regarding CE Bomb Script.

### ISSUE THREAD

**Issue by Wewlad01** [Fate-Grand-Automata/FGA#1294] opened 2022-08-16 17:16 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Hi there, I've been eager to use such fuction, but after looking around, I can't seem to install it. Any advice on this?  Thanks in advance.

**Comment by reconman** [comment] 2022-08-16 17:39
Duplicate of #998

**Closed** 2022-08-16 17:39 UTC
Labels: question
