### ISSUE TITLE
Support Mode "First" : Avoid NPC

### ISSUE THREAD

**Issue by Cascadess** [Fate-Grand-Automata/FGA#742] opened 2021-06-22 16:29 UTC
When choosing support, first mode works best, except when useless NPC gets in the way.

Thank you

**Comment by MathewSachin** [comment] 2021-06-22 17:26
Duplicate of #620, #738, #679

#620 is still open.

Quoting my reply on #679:
> You already have another issue open for this. Please don't spam.

I'm banning you from this repository to prevent further spam.

**Closed by MathewSachin** 2021-06-22 17:26 UTC
