### ISSUE TITLE
FGA fails to determine card type during card selection

### ISSUE THREAD

**Issue by Mizu0025** [Fate-Grand-Automata/FGA#1469] opened 2022-12-02 00:53 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1892

### Describe the bug

Occasionally during battle FGA fails to determine the card type, when selecting Noble Phantasm cards to use, and either selects the desired NP card anyway or just selects face cards instead.

Steps taken to trigger bug:
1. Start FGA at the beginning of a battle
2. Run a combat script to use buffing skills on a character, before attacking 3 waves of enemies with the character's noble phantasm
3. Error occurs occasionally during card selection phase each wave. It isn't a constant 'every time' thing, however.

### Video

https://photos.app.goo.gl/x9QSoaf5bac9EaJk6

### Device model

Pixel 7 Pro

### Android version

13

### Screen size

1080x2400

### RAM

12GB

**Comment by Mizu0025** [comment] 2022-12-02 00:56
I tried recording video using the screen recorder function on Android 13, like suggested, but FGA threw up and error and crashed whenever I attempted it. So instead you've got shaky cam video of my phone screen, taken via another phone recording video.

I also tried the 'custom detection area' suggested [here](https://github.com/Fate-Grand-Automata/FGA/issues/1347) for the Pixel 7 Pro, but it didn't seem to improve things; if anything it broke functionality, as it often failed to click anything vs default settings.

**Comment by vybze** [comment] 2022-12-02 02:12
Can you post your battle script?

**Comment by Mizu0025** [comment] 2022-12-02 04:48
> Can you post your battle script?

Sure, here you go.

> {"autoskill_notes":"Caster Artoria, Summer Mordred, Tamamo","support_fallback":"First","card_priority":"WA, WB, WQ, A, B, Q, RA, RB, RQ","autoskill_name":"QP Farming","support_pref_ce_mlb":true,"autoskill_party":"5","autoskill_support_class":"Rider","auto_skill_rearrange_cards":"F","spam_x":"[{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"Spam\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}},{\"a\":[{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"},{\"a\":[1,2,3],\"b\":\"None\",\"c\":\"None\"}],\"b\":{\"a\":[1,2,3],\"b\":\"None\"}}]","support_pref_ce_list":["Bella Lisa.png"],"servant_priority":"1,2,3,4,5,6","also_check_all":true,"auto_skill_brave_chains":"None","autoskill_cmd":"ab2c2dfgi25,#,5,#,5"}

**Comment by vybze** [comment] 2022-12-02 07:49
Turn off spamming and see what happens

**Comment by Mizu0025** [comment] 2022-12-02 10:44
I turned off the NP/skill spamming for the autobattle script, but the card error still appears.

**Comment by reconman** [comment] 2022-12-02 13:22
Duplicate of #1450

**Closed** 2022-12-02 13:22 UTC
Labels: bug
