### ISSUE TITLE
Can I set required NP level for servants?

### ISSUE THREAD

**Issue by sasakiyori** [Fate-Grand-Automata/FGA#1723] opened 2023-12-27 02:30 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Sometimes I need a high NP level servant from friends as a main attacker (e.g. 90++).  Low NP level servants may cause insufficient damage.

Is it possible to set the required servant NP level for detection?

**Comment by reconman** [comment] 2023-12-27 02:50
Duplicate of #334

**Closed by reconman** 2023-12-27 02:50 UTC
Labels: question
