### ISSUE TITLE
order change doesn't work

### ISSUE THREAD

**Issue by SORAxSHIRO** [Fate-Grand-Automata/FGA#648] opened 2020-12-29 15:35 UTC
- [ yes] I tested the latest release
- [ y] I looked at other issues (even the closed ones)
- [ y] I read the [Troubleshooting Guide]
- [ y] I'll fill this template properl

**Describe the bug**
order change, click in wrong area '-' 

**Video**

https://user-images.githubusercontent.com/76656461/103295131-fd497200-49fb-11eb-9137-dbc507ca9ac1.mp4

**Device Info (please fill at-least 'Device model'):**
 - Device model: [ Huawei p20]
 - Screen size: []
 - Android Version: [android 10, emui 10]
 - RAM: [4 ram]

**Comment by reconman** [comment] 2020-12-29 15:42
Duplicate of #571 

If you're really using the latest canary build, then add a comment there.

**Closed by reconman** 2020-12-29 15:42 UTC
Labels: bug

**Comment by SORAxSHIRO** [comment] 2020-12-29 16:23
i fix it, but by other way, thx

**Comment by MathewSachin** [comment] 2020-12-29 16:28
what other way?
I had pushed a Master skill fix around the same time you opened this issue. Did that fix?

**Comment by SORAxSHIRO** [comment] 2020-12-29 16:35
from phone settings, in notch setting ![Screenshot_20201229_183423.jpg](https://user-images.githubusercontent.com/76656461/103299116-81075c80-4a04-11eb-80f0-dd676a15efdd.jpg)
i turn show notch to on, and from app setting, ignore notch calculation

**Comment by SORAxSHIRO** [comment] 2020-12-29 16:37
not from the last app update, i think the phone ignore notch by himself, make this issus 😗
