### ISSUE TITLE
Card detection fails for super buffed Support Servants

### ISSUE THREAD

**Issue by Alucardan2** [Fate-Grand-Automata/FGA#1076] opened 2022-01-17 14:59 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1599

### Describe the bug

So I have been seen the message type error again but somehow it picks np chain, well 9 out of 10 times at least, checked the app and all values are set to default. 

Tested in NA but had no problem, or at least didn't see it happen.

### Video

https://youtu.be/2F6LL3TuyMw

### Device model

Xiaomi redmi note 10s

### Android version

11

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment] 2022-01-19 22:47
Morgan with a veil is too dark for image detection. Use another ascension for better results.

**Comment by Alucardan2** [comment] 2022-01-19 22:59
I was suspecting that. How can I change the look of the support servant. That is the only Morgan with a broken Kscope as an event support, the rest uses other CES

**Comment by reconman** [comment] 2022-01-20 06:26
My assumption was wrong. After sleeping, I now see the real issue. Buff icons are covering the Support icon in the top right.

I currently have no idea how this can be solved.

**Comment by Alucardan2** [comment] 2022-01-20 13:19
Ahh, so when the superbuff servant is owned it doesn't make that mistake. My new JP account doesn't have a main dps farmer.

**Comment by AKSoo** [comment] 2022-01-21 08:51
Duplicate of #913. Kind of a big deal since it is very common to have super buffed farmers in events. Makes servant priority and brave chain features almost useless.

**Comment by Alucardan2** [comment] 2022-01-21 11:39
> Duplicate of #913. Kind of a big deal since it is very common to have super buffed farmers in events. Makes servant priority and brave chain features almost useless.

I know, but the reason I found it weird was that it didn't happen with my NA Dantes. So I don't know if it only happens with supports or with a Veil Morgan only.

**Comment by reconman** [comment] 2022-01-21 12:59
Definitely not a duplicate, support servants use a different card detection logic.

**Comment by Jeff-M-Hsu** [comment] 2022-01-24 22:35
> I know, but the reason I found it weird was that it didn't happen with my NA Dantes. So I don't know if it only happens with supports or with a Veil Morgan only.

This is currently happening to me with Jeanne Archer in the latest build, she stops being detectable with this many buffs.
![image](https://user-images.githubusercontent.com/22153012/150876354-f78fa956-cae6-4018-8721-3e96b1654ac5.png)

**Comment by Alucardan2** [comment] 2022-01-24 22:57
Oh god, that's going to be annoying.

**Comment by reconman** [comment] 2022-01-24 23:32
@Jeff-M-Hsu Anything affecting non-Support servants is not part of this bug.

I'll need a different bug report for your issue with a video. I need to see exactly what happens.

**Comment by ArthurKun021** [comment] 2022-09-28 00:24
> @Jeff-M-Hsu Anything affecting non-Support servants is not part of this bug.
> 
> I'll need a different bug report for your issue with a video. I need to see exactly what happens.

Kinda having the same problem as him, the super buffed servant is not being able to be detected.

Weirdly enough, there are some cases for me where the superbuffed servants can't be detected after the first time in wave 3 but whenever it needs to brave chain it can somehow go back to normal

**Comment by yoyorast1** [comment] 2022-12-24 11:09
Having the same issue right now.

**Closed** 2023-12-26 16:48 UTC
Labels: bug

**Comment by reconman** [comment] 2023-12-26 16:51
Fixed the issue with a new optional feature in More Options -> Battle

![image](https://github.com/Fate-Grand-Automata/FGA/assets/12360257/d51b2c2d-ac38-4c9b-a8d8-820d474df03d)
