### ISSUE TITLE
Phone Suddenly shutdown 

### ISSUE THREAD

**Issue by balonbao247** [Fate-Grand-Automata/FGA#1465] opened 2022-11-30 15:49 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

My redmi note 11 Suddenly shutdown while using FGA

**Comment by reconman** [comment] 2022-11-30 17:01
Duplicate of #1454

**Closed** 2022-11-30 17:01 UTC
Labels: question
