### ISSUE TITLE
Build 1551 - Wave 3 script not running as intended + material capture screen not working after NA fullscreen update

### ISSUE THREAD

**Issue by JusKIdding** [Fate-Grand-Automata/FGA#950] opened 2021-11-16 13:24 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1551

### Describe the bug

Wave 3 script does not work after NA widescreen update.  For wave 3, it decides to go with face cards instead of running the selected skills.

From video, you can see it's only on wave 4 it decides to run the wave 3 script.

In addition, the material "capture" screen does not work, which leads the automata to be stuck on the rewards screen. 

Screenshot of my script setup for Dust farm
Position:

- Wave 1
1. Servant 3 - 3rd Skill 
2. Servant 3 NP

- Wave 2
1. Servant 3 - 3rd [to Servant 1] + 1st Skill [to Servant 1]
2. Servant 1 NP

- Wave 3  
1. Servant 2 - 3rd [to Servant 1] + 1st [to Servant 1] + 2nd skill 
2. Servant 3 - 3rd skill
3. Servant 1 - 3rd + 2nd + 1st skill
4. From Mystic Code - 1st skill  
5. Switch Servant 2 to Servant 1 (backline)
6. Servant 2 - 1st skill + 3rd skill [to Servant 1]
7. Servant 1 NP

![Screenshot_20211116-211230_FGA (CI)](https://user-images.githubusercontent.com/41385292/141991873-5cbd6184-ac28-4540-9243-fbc9fe16eb5f.jpg)

### Video

[Video to the issue](https://youtu.be/24MD_9TrXp8)

### Device model

Samsung Galaxy J7 Prime

### Android version

8

### Screen size

1080 x 1920

### RAM

3 GB

**Comment by reconman** [comment] 2021-11-16 13:25
Duplicate of #948

**Closed by reconman** 2021-11-16 13:25 UTC
Labels: bug
