### ISSUE TITLE
Skills can be used in the first round, but not in the second round

### ISSUE THREAD

**Issue by BloodBuster** [Fate-Grand-Automata/FGA#1675] opened 2023-09-08 14:24 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

2152

### Describe the bug

在第二回合时无法使用设定好的技能，只使用指令卡
In the second round, the set skills cannot be used, only the command card is used
![Screenshot_20230908_222205](https://github.com/Fate-Grand-Automata/FGA/assets/142583079/6640c7c4-d596-4f23-a7e4-563b2ec36c7d)

### Video

Uploading mmexport1694182654323.mp4…

### Device model

vivo iQOO Neo5

### Android version

13

### Screen size

2400x1080

### RAM

12GB

**Comment by reconman** [comment] 2023-09-08 15:10
You opened 2 issues at the same time?

Duplicate of #1676

**Closed by reconman** 2023-09-08 15:10 UTC
Labels: bug
