### ISSUE TITLE
quest start button doesnt work until change team

### ISSUE THREAD

**Issue by jins9** [Fate-Grand-Automata/FGA#1247] opened 2022-07-14 03:09 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1721

### Describe the bug

quest start button doesnt work until change team
I read https://github.com/Fate-Grand-Automata/FGA/issues/465 this but I find some people solved this problem by increasing the resolution. So I think It's not just a game lssuse. I also tried to solve this problem by increasing the resolution, but this is not possible with my mobile device

ps and I dont know why but I faild to record my screen so I brought a similar video

### Video

https://www.youtube.com/watch?v=q_QZFBIWgDU

### Device model

Galaxy Tab S8

### Android version

12

### Screen size

2560 x 1600

### RAM

8gb

**Comment by reconman** [comment] 2022-07-15 19:00
Duplicate of #993

If you can't record a video, you should not just use a random video you found somewhere. I was confused why FGO has blue bars and why the FGA stop button looks weird.

**Closed** 2022-07-17 19:15 UTC
Labels: bug
