### ISSUE TITLE
Add option to stop FGA after X CE drops

### ISSUE THREAD

**Issue by berserk64** [Fate-Grand-Automata/FGA#1325] opened 2022-08-25 15:56 UTC
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

I see the game already has a counter for number of CE dropped when you stop FGA, if possible to add a stop on X number of CE dropped. During lotto stopping after X amount of CE would be quite a nice feature to have to mlb the CE as needed and be more efficient

Thanks

**Comment by reconman** [comment] 2022-08-25 17:22
Duplicate of #1044

**Closed by reconman** 2022-08-25 17:22 UTC
Labels: enhancement
