### ISSUE TITLE
无法识别彩色卡片

### ISSUE THREAD

**Issue by LuJiong123** [Fate-Grand-Automata/FGA#1260] opened 2022-07-27 23:18 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1742

### Describe the bug

Thanks for your efforts, the problem of identifying servant has been solved, but it is found that the color card recognition fails in the process of use. It seems that only blue cards can be recognized.The red cards and green cards can not be recognized.

### Video

![51685EE9-7A15-429A-BD64-843C4426A46B](https://user-images.githubusercontent.com/110135657/181388462-05e2426c-8264-4560-aa36-b99b301b65b8.jpeg)

### Device model

xiao mi6

### Android version

7

### Screen size

1280*720

### RAM

3gb

**Comment by reconman** [comment] 2022-07-29 10:09
Duplicate of #1258

**Closed by reconman** 2022-07-29 10:09 UTC
Labels: bug
