### ISSUE TITLE
Send friend request automatically after battle (plz :'D)

### ISSUE THREAD

**Issue by GreatIkeaChair** [Fate-Grand-Automata/FGA#1145] opened 2022-04-05 22:52 UTC
### Preparation

- [x] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

It would be so helpful. Like, I use FGA a lot to farm but in turn I don't really have many friends (big sad) so when I'm playing against bosses I don't have many friends supports to choose from. 
Like you would make me so happy (and my life a bit easier) if you added this feature.

**Comment by reconman** [comment] 2022-04-06 05:21
Duplicate of #977

**Closed** 2022-04-06 05:21 UTC
Labels: enhancement
