### ISSUE TITLE
FGA stop itself by selecting support under the stop button on Nox

### ISSUE THREAD

**Issue by ShibaShika** [Fate-Grand-Automata/FGA#750] opened 2021-06-24 10:57 UTC
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
Only Nox has this problem.
If position of the target support just at the most bottom, and FGA want to choose it, then FGA will stop script by itself.

I tested on my android phone, and FGA can't recognize target at the same position, so this problem never happened.
(FGA will never choose support under the stop button)

I move FGA button to other position to solve this problem temporarily, but every time I restart Nox I need to move button again.

**Screenshots**
![FGA stop itself](https://user-images.githubusercontent.com/40266069/123233236-77bb0080-d50c-11eb-9d24-f72e7fb3b92f.png)

**Video**

https://user-images.githubusercontent.com/40266069/123238546-23fee600-d511-11eb-885d-fbe1b58578e9.mp4

**Device Info:**
 - Device model: NoxPlayer 7.0.1.2 32-bit
 - Screen size: 1920x1080
 - Android Version: 7.1.2
 - RAM: 4GB
 - FGA Version: 1360

**Comment by MathewSachin** [comment] 2021-06-24 11:07
Duplicate of #578

**Closed by MathewSachin** 2021-06-24 11:07 UTC
Labels: bug

**Comment by ShibaShika** [comment] 2021-06-24 13:28
Oh, I search with wrong keywords, so I didn't see that issue. 
Sorry about that, and thanks for your reply.

After I read that, I solved it with changing nox DPI to 240.
This makes FGA button size smaller to avoid clicking it.
If this problem still exists, maybe try lower DPI.
