### ISSUE TITLE
The new version still won't work

### ISSUE THREAD

**Issue by 1717231** [Fate-Grand-Automata/FGA#1263] opened 2022-07-28 14:36 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1023

### Describe the bug

Not only the selection of friends to help the follower, but also the release of follower skills are problematic

### Video

https://www.instagram.com/tv/Cgjyqr5F_VQ/?igshid=MDJmNzVkMjY=

### Device model

vivoiQOO5

### Android version

12

### Screen size

2376×1080

### RAM

128GB

**Comment by reconman** [comment] 2022-07-29 10:08
Duplicate of #1258

**Closed by reconman** 2022-07-29 10:08 UTC
Labels: bug
