### ISSUE TITLE
the FGA get stuck at friend support select 

### ISSUE THREAD

**Issue by BIGLbruh** [Fate-Grand-Automata/FGA#945] opened 2021-11-12 13:44 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1551

### Describe the bug

FGA don't select the friend support no matter what i do i even try to  reinstall but no luck 

### Video

https://user-images.githubusercontent.com/92425957/141476444-96db4773-1114-46e1-9be4-64adab5c36f7.mp4

### Device model

samsung galaxy a30

### Android version

9

**Comment by jcdeoferio** [comment] 2021-11-13 04:26
Duplicate of !943 ?

**Comment by BIGLbruh** [comment] 2021-11-13 12:11
> Duplicate of #943 ? 

his bug look different tho

**Comment by Unumbium** [comment] 2021-11-16 16:52
I got the same issue, the last update of the game moved the UI and makes FGA go apesht

**Comment by brightEcho** [comment] 2021-11-17 09:28
I have the same issue as well. Using a samsung s20 galaxy plus ultra.

**Comment by mersonff** [comment] 2021-11-17 19:58
Same issua with OnePlus 9 Pro

**Comment by Tom3kk** [comment] 2021-12-06 20:36
I have the same issue on Nox of all things.

**Comment by reconman** [comment] 2021-12-06 21:43
The video above is probably the same as #943, but FGA's video recorder wasn't used so FGA couldn't see anything.

**Closed by reconman** 2021-12-06 21:43 UTC
Labels: bug

**Comment by Euphy14** [comment] 2021-12-24 20:36
It still not fixed in poco x3
