### ISSUE TITLE
Script misclicking, getting stuck on servant status

### ISSUE THREAD

**Issue by Oswaldnull** [Fate-Grand-Automata/FGA#1045] opened 2021-12-25 00:43 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1592

### Describe the bug

Script gets stuck on servant 1 status, attempts to click battle, gets stuck again permanently

### Video

[Video](https://youtu.be/Yc6EzwWeUk8) 

### Device model

Pixel 4A 5G

### Android version

12

### Screen size

2340x1080

### RAM

128GB

**Comment by Kyonyuu** [comment] 2021-12-25 20:29
#1038 
> * [x]  I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))

**Comment by reconman** [comment] 2021-12-25 20:36
Duplicate of #1041

**Closed by reconman** 2021-12-25 20:36 UTC
Labels: bug
