### ISSUE TITLE
galaxy note20 Can't run CN

### ISSUE THREAD

**Issue by 556yoyo** [Fate-Grand-Automata/FGA#995] opened 2021-12-07 23:59 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1567

### Describe the bug

My english is bad
So use the internet machine translation
I use galaxy note20 5G
Test in the CN version

None of the detection areas can correspond to the location
![Screenshot_20211208-073442_-](https://user-images.githubusercontent.com/68665574/145123326-2cc1369f-d138-4049-b56f-770cd0ccf32f.jpg)

The program is completely useless in this area
As for combat, most of them can’t be caught.
![Screenshot_20211208-074157_-](https://user-images.githubusercontent.com/68665574/145123342-b49a4f62-5e65-4110-8f03-fe9d0591d64a.jpg)

Would you like to ask how to deal with the improvement?

### Video

https://youtu.be/-U3vIErZCiM

### Device model

galaxy note20 5G

### Android version

11

**Comment by reconman** [comment] 2021-12-10 19:04
Duplicate of #938.

Set FGO and FGA to fullscreen mode in your system settings and maybe you also have to activate 忽略刘海 in FGA's settings.

**Closed by reconman** 2021-12-10 19:04 UTC
Labels: bug
