### ISSUE TITLE
Ember collection from Present Box mistakes teen numbers as selections

### ISSUE THREAD

**Issue by SodaCopper** [Fate-Grand-Automata/FGA#1491] opened 2022-12-18 22:54 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

When running the automated selection in the present area, selections on 11, 12, 13, and 14 will be made. This correlates to the limiter value set; if the limiter is set to 3, 11,12, and 13 will be selected. 

### Video

https://youtu.be/l0ftbkr57Cw

### Device model

Samsung galaxy note9

### Android version

10

### Screen size

2960x1440

### RAM

8gb

**Comment by reconman** [comment] 2022-12-18 23:02
Duplicate of #1009

**Closed by reconman** 2022-12-18 23:02 UTC
Labels: bug
