### ISSUE TITLE
Battle Configs breaking on Wave 2

### ISSUE THREAD

**Issue by Djinnistorm** [Fate-Grand-Automata/FGA#954] opened 2021-11-16 18:25 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1554

### Describe the bug

Two previously working battle configs both run into the same problem after the recent updates. The clear starts normally, picks support, does wave 1 properly. Wave two it skips all skill usage and starts facecarding. Doesn't even seem to attempt to select skills, or miss buttons. Restarted the app, rewrote the turn in one of the Battle Configs, still nothing. Doesn't seem to matter if I start the script from the combat screen or the support screen. Let me know what other information I can get for you to help you help me. Thanks for the help and the solid application.

### Video

https://streamja.com/05n4j

### Device model

Bluestacks 4

### Android version

7

### Screen size

1600x900

### RAM

4GB

**Comment by Djinnistorm** [comment] 2021-11-16 18:44
Here's one of the configs in question, in case that helps at all
[--Lantern.zip](https://github.com/Fate-Grand-Automata/FGA/files/7548990/--Lantern.zip)
:

**Comment by JoshStegmaier** [comment] 2021-11-16 18:52
I'm having the same issue. Also using Bluestacks.

**Comment by reconman** [comment] 2021-11-16 19:00
Duplicate of #953

**Closed by reconman** 2021-11-16 19:00 UTC
Labels: bug

**Comment by Djinnistorm** [comment] 2021-11-16 19:42
Ah someone else made the same issue while I was getting the video.  Thanks.
