### ISSUE TITLE
Friend names and Preferred servant

### ISSUE THREAD

**Issue by TMP7ML** [Fate-Grand-Automata/FGA#1445] opened 2022-11-13 04:25 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Is there any way to make Automata pick A servant from specific friends?

What I'm trying to do is pick a specific servant with high NP level, since automata doesn't have this feature yet I used to use the Support Image Maker to grab the name of my friends that had said servant at NP3 or above. 
But with the implementation of triple supports other servants can appear in the list first, and since automata only checks the friend name it will pick the first servant under that name instead of the one I want.
I'm aware that "Friends Only" is an option in the Preferred section, but that option will pick any friend with that servant, regardless of its NP level.

**Comment by reconman** [comment] 2022-11-14 18:33
I guess the only long-term solution is combining Friend selection with Servant and CE selection.

As a workaround, you could try sorting their servants by HP or Attack, but if they swap any servant, FGA will pick the incorrect one again.

**Comment by reconman** [comment] 2023-06-16 21:14
Duplicate of #1065

**Closed as not planned by reconman** 2023-06-16 21:14 UTC
Labels: question
