### ISSUE TITLE
FGA not choosing support servant

### ISSUE THREAD

**Issue by rchan3** [Fate-Grand-Automata/FGA#1264] opened 2022-07-29 02:41 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1742

### Describe the bug

Game updated and servant selection didn't work. Updated FGA to BUILD: 1742 and restarted my phone. Still have the same issue. 

### Video

https://user-images.githubusercontent.com/57269877/181671469-f62eafa5-c9c1-4f05-b987-3e2ed79518b1.mp4

### Device model

Galaxy S10+

### Android version

12

### Screen size

2280x1080

### RAM

8GB

**Comment by XaviorLord** [comment] 2022-07-29 03:39
i faced the same issue, update 1742 cant help

**Comment by William-02-02** [comment] 2022-07-29 10:06
可以试试用1742修改游戏区域模式参数  更多选项 进阶 GameAreaMode 改成custom

**Comment by reconman** [comment] 2022-07-29 10:09
Duplicate of #1258

**Closed by reconman** 2022-07-29 10:09 UTC
Labels: bug
