### ISSUE TITLE
Script being stopped without consent

### ISSUE THREAD

**Issue by jochuan** [Fate-Grand-Automata/FGA#672] opened 2021-01-19 14:33 UTC
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I am playing on Bluestacks and sometimes the script stops and says that it was stopped by the user even with me doing nothing. Looks like this is random sometimes it runs 6 times and other it runs only one or 2 before stopping. Also it only stops in the support selection screen.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: The emulator is using a Samsung Galaxy S8 plus
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by jochuan** [comment] 2021-01-19 14:39
![Bug](https://user-images.githubusercontent.com/11268912/105048676-95120d00-5a4a-11eb-81d1-390a0f908c35.png)
I think that i found the cause of this issue, when the script is looking for another skadi in the support selection screen it needs to scroll down the page and if he founds skadi in the bottom it ends up touching the stop button instead of the her.

**Comment by reconman** [comment] 2021-01-19 15:55
For your situation, I would recommend changing your screen size to non-16:9 according to this guide: https://support.bluestacks.com/hc/en-us/articles/360021368872-How-can-I-customize-BlueStacks-4

For example, 1400x720 or something similar.

**Comment by MathewSachin** [comment] 2021-01-19 16:20
Duplicate of #578

**Closed** 2021-01-20 13:48 UTC
Labels: bug

**Comment by jochuan** [comment] 2021-01-22 13:18
Sorry for bumping this issue but after i changed my screen size the app doesn't scroll down to look for skadi anymore and instead it updates the support screen and wait for a skadi to appear, but this can take a long time and sometimes it choses different servants.
