### ISSUE TITLE
Fail to Detect NP Card Starting 2nd Wave? 

### ISSUE THREAD

**Issue by ghost** [Fate-Grand-Automata/FGA#1215] opened 2022-06-16 18:06 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

TW

### FGA build number

1701

### Describe the bug

Hello, 
I usually farm with double castoria + lambdaryllis setup, but after new update, app does not seem to detect NP card starting on second wave of level... 
I am running on an emulator that isn't listed, but prior to this update on TW server it functioned perfectly for last event with this exact setup and script. 
The battle script is attached [here](https://github.com/Fate-Grand-Automata/FGA/files/8921355/test.txt), and along with a video that stops after the NP is not chosen (as I don't want to waste AP and restarted to farm manually after.)

### Video

https://youtu.be/A9BH9UcsrfA

### Device model

LDPlayer 4.0.81

### Android version

7

### Screen size

1600x900

### RAM

4GB

**Comment by reconman** [comment] 2022-06-16 18:34
Duplicate of #1214

**Closed as not planned** 2022-06-16 18:34 UTC
Labels: bug
