### ISSUE TITLE
Boost item  not selected

### ISSUE THREAD

**Issue by Silversxs** [Fate-Grand-Automata/FGA#1086] opened 2022-02-01 14:55 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1611

### Describe the bug

Event boost item select doesn't work properly

### Video

https://youtu.be/nNqAkVdpVik

### Device model

Xiaomi redmi note 8 pro

### Android version

11

### Screen size

1080 x 2340

### RAM

6gb

**Comment by TheDunntist** [comment] 2022-02-03 14:56
Also suffering from this problem.

**Comment by reconman** [comment] 2022-02-03 16:31
It's not only the item selection but also the mana prism reward screen.

**Comment by TheDunntist** [comment] 2022-02-03 17:59
I hadn't even gotten far enough to hit that issue but I can see that being just as much a problem.

**Comment by reconman** [comment] 2022-02-03 18:01
What do you mean? Just tap on the item, then let FGA finish the quest.

**Comment by TheDunntist** [comment] 2022-02-03 18:33
Oh I was trying to do fully automated farming with 0 input so I could leave it running overnight. So needing any kind of input to proceed ruined that plan.

**Comment by Sparlchemy** [comment] 2022-02-03 22:54
I can confirm that this is a problem, regardless of what your settings for Boost Item is. It can't even skip it.

**Comment by Megalobst** [comment] 2022-02-07 21:33
Confirm all the above, seems like boost function is broken.

**Comment by hajimememe69420** [comment] 2022-02-09 14:13
If you don't want to use booster item in the bugged version. You can choose begin without booster item and go like normal. The repeat from then they won't asks for item booster.

**Comment by reconman** [comment] 2022-02-26 09:34
I didn't have time to look into this issue, I'm closing it for now since the event is already over and I don't know if any future events will cause the same bug.

**Closed by reconman** 2022-02-26 09:34 UTC
Labels: bug
