### ISSUE TITLE
Can not select friend servant in selecting friend servant page

### ISSUE THREAD

**Issue by fenfam** [Fate-Grand-Automata/FGA#1229] opened 2022-07-05 08:05 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1707

### Describe the bug

FGA could automatically select the battle stage, however, when showing the scene of friend servant selecting, it just suddenly stops. The scene seems freezed.

### Video

https://user-images.githubusercontent.com/30427210/177280369-16e0bc86-208e-48d6-8cad-4251931edd64.mp4

### Device model

Realme GT

### Android version

12

### Screen size

2400*1080

### RAM

12GB

**Comment by reconman** [comment] 2022-07-05 08:07
Duplicate of #1211

**Closed by reconman** 2022-07-05 08:07 UTC
Labels: bug
