### ISSUE TITLE
Failed to determine card type on buffed own servant

### ISSUE THREAD

**Issue by kiritox18** [Fate-Grand-Automata/FGA#1335] opened 2022-08-27 08:20 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1801

### Describe the bug

My own Sieg when buffed a bunch of type can not perform a brave chain post NP because of "Unable to determine card type" error. I have even put the similarity to 70% and even then it does not work.

### Video

[Stream link](https://streamable.com/nur5rg)

### Device model

Oneplus 7T

### Android version

11

### Screen size

1080x2400

### RAM

6GB

**Comment by reconman** [comment] 2022-08-27 09:33
In this frame FGA checks if Sieg is alive and the invincibility buff is blocking his face.

![image](https://user-images.githubusercontent.com/12360257/187024309-38ef81aa-ccff-4ca9-9e99-6a8cb3c6d250.png)

I'll fix it later, don't have time right now.

Duplicate of #1082

**Closed by reconman** 2022-08-27 09:33 UTC
Labels: bug
