### ISSUE TITLE
Unexpected Error: Index: 1, Size: 1 (Script Crash)

### ISSUE THREAD

**Issue by Github-Confounds-Me** [Fate-Grand-Automata/FGA#976] opened 2021-11-23 17:39 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

![FGA_Error](https://user-images.githubusercontent.com/94634122/143073864-e6133a6b-5a87-4510-9864-9119e00fe01b.jpg)

Error + script crash happens during the third wave after all skills have been applied to the DPS. This occurs on both Bluestacks 4 and Bluestacks 5 using various screen resolutions.

Clicking on “Copy” on the error message gives this info…

null

e4.a$b
at e4.a.b(AutoBattle.kt:3)
at d5.c.q(EntryPoint.kt:3)
at r5.a.run(Thread.kt:1)

Might be related to the previously fixed Unexpected Error: Collection is empty issue found here #915 ?

### Video

https://user-images.githubusercontent.com/94634122/143074497-f574935f-5146-4bb0-be07-f969a17e8646.mp4

[Link to full video](https://youtu.be/b1Lphii_BP8)

### Device model

Bluestacks 4 + Bluestacks 5 (OnePlus 5)

### Android version

7

### Screen size

960 x 540, 1600 x 900, 2560 x 1440 etc

### RAM

20 GB

**Comment by reconman** [comment] 2024-01-06 14:41
Should be fixed now, was caused by a combination of 1 card before NP, brave chain with NP and rearrange cards.

**Closed by reconman** 2024-01-06 14:41 UTC
Labels: bug
