### ISSUE TITLE
CN UI changes

### ISSUE THREAD

**Issue by Kyonyuu** [Fate-Grand-Automata/FGA#865] opened 2021-09-08 03:31 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1488

### Describe the bug

UI changes made battle script being bugged or not working, wave 1 works just fine, wave 2+, no.

### Video

https://www.youtube.com/watch?v=7TiKYDYLNoc

### Device model

LGK10

### Android version

7

**Comment by Kyonyuu** [comment] 2021-09-08 03:47
Also tried in 1492 build, same problem.

**Comment by reconman** [comment] 2021-09-08 04:49
Do you know what changed? I noticed that the stage counter area has moved.

**Comment by Kyonyuu** [comment] 2021-09-08 04:56
Now fgo can be in full-screen(like JP)
most changes are the same as JP(Before passive skills were added)
don't know much more than that...
i will see if they changed the moonrunes position...

**Comment by Kyonyuu** [comment] 2021-09-08 04:58
yeah, they changed the position of "wave/turn"

**Comment by Kyonyuu** [comment] 2021-09-08 05:06
oh yeah, tried other builds(Party) with other Mystic Code and using skills on the second turn it works, dunno why though...(should i record?)

**Comment by MathewSachin** [comment] 2021-09-08 06:40
Looks like the wide screen update.
We need to verify how notch is handled though.
Will need someone playing on CN to post a video on a phone with a notch.

**Comment by NepPure** [comment] 2021-09-08 07:36
> Looks like the wide screen update.
> We need to verify how notch is handled though.
> Will need someone playing on CN to post a video on a phone with a notch.

https://github.com/Fate-Grand-Automata/FGA/issues/861#issuecomment-914994332

 position of "wave/turn" and checkout page.

I only found these for the time being

**Comment by reconman** [comment] 2021-09-08 07:55
Duplicate of #861

**Closed by reconman** 2021-09-08 07:55 UTC
Labels: bug
