### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Alphacentariprime** [Fate-Grand-Automata/FGA#807] opened 2021-08-07 05:24 UTC
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [x ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required
Having issue where servant picker won't select the correct servant when the max skills is selected 
![Screenshot_20210807-012305_FGA (CI)](https://user-images.githubusercontent.com/83358830/128589097-dc44f340-9a23-46ae-9dca-ff8b942bbd0b.jpg)

https://user-images.githubusercontent.com/83358830/128589100-319117ce-f5bf-4590-9d07-4850acc9de90.mp4

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Samsung galaxy S10+]
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by MathewSachin** [comment] 2021-08-07 05:37
Duplicate of #796 😞

**Closed by MathewSachin** 2021-08-07 05:37 UTC
Labels: bug
