### ISSUE TITLE
Support Image Maker not functioning with new event CE

### ISSUE THREAD

**Issue by JusKIdding** [Fate-Grand-Automata/FGA#851] opened 2021-09-02 12:46 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1483

### Describe the bug

Used Support Image Maker for Scenic Beauty Craft Essence.

However, in the Support List, it does not detect the CE at all.

### Video

[Recording evidence:](https://youtu.be/6hQcJRqlarE)

![Screenshot_20210902-203310_FGA (CI)](https://user-images.githubusercontent.com/41385292/131845084-1b833c5a-8b3d-4e47-b33c-adb8181b42a6.jpg)

### Device model

Samsung Galaxy J7 Prime

### Android version

8

### Screen size

1080 x 1920

### RAM

3 GB

**Comment by reconman** [comment] 2021-09-02 12:47
Your video is private, not unlisted.

**Comment by JusKIdding** [comment] 2021-09-02 12:49
> Your video is private, not unlisted.

Hi, I've fixed it. It's unlisted now. So sorry for that minor hiccup.

**Comment by JusKIdding** [comment] 2021-09-02 14:50
The Friend option selection is working well. It's only the event CE not detecting at all, strange. 

Thanks for creating this app, it's been helping me rest while I work hahaa.

**Comment by reconman** [comment] 2021-09-02 15:55
I'm seeing that 10/10/10 does not seem to work.

**Comment by reconman** [comment] 2021-09-02 15:56
Duplicate of #850

**Closed by reconman** 2021-09-02 15:56 UTC
Labels: bug

**Comment by JusKIdding** [comment] 2021-09-02 16:09
Thanks - I didn't know it's a duplicate issue.

**Comment by reconman** [comment] 2021-09-03 21:28
Btw, just use event CE filters built into FGO, no need to create new support images.
