### ISSUE TITLE
Screen tap issue on the top right corner of the screen

### ISSUE THREAD

**Issue by Goharn** [Fate-Grand-Automata/FGA#732] opened 2021-06-17 04:16 UTC
Before opening an issue:
- [-] I tested the latest release
- [-] I looked at other issues (even the closed ones)
- [-] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [-] I'll fill this template properly

**Describe the bug**
Screen tap the top right corner of the screen once during every servant skill usage and once during every NP card select.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Xperia XZs
 - Screen size: 1920*1080
 - Android Version: Android 8
 - RAM: 4GB

**Comment by MathewSachin** [comment] 2021-06-17 05:09
Duplicate of #413

**Closed by MathewSachin** 2021-06-17 05:09 UTC
Labels: bug, duplicate
