### ISSUE TITLE
My phone crashed when updated to build 1892 

### ISSUE THREAD

**Issue by storiixp** [Fate-Grand-Automata/FGA#1464] opened 2022-11-28 04:14 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1892

### Describe the bug

FGA been working fine on older build.
But after I updated to build 1892 today and used it for 5 minutes and then my phone crashed. And it keep happening when i use FGA.

I'm sure that it's because of this build since i used the old version to farm in lotto event all night before. Also my phone doesn't overheat when it crashed.

Is there a way to access older build? I can't find it anywhere.

Hopefully this will get fixed and thank you for this useful app.

### Video

none. 

### Device model

Xiaomi Redmi note 9s

### Android version

11

### RAM

6GB

**Comment by Skyjersey** [comment] 2022-11-29 05:18
Here's build 1871 see if it crashes again.

**Comment by Jordan17FGO** [comment] 2022-11-30 04:13
@Skyjersey It seems that buld 1871 works just fine without crashing. and the problem lies within build 1892. I tried and it works. Thank you

**Comment by storiixp** [comment] 2022-11-30 06:59
> Here's build 1871 see if it crashes again. https://www.mediafire.com/file/gsfjw4g2xl04lk0/FGA_Build_1871.apk/file

It's working perfectly. Thank you!

**Comment by reconman** [comment] 2022-11-30 07:24
Duplicate of #1454

I'll look into it this week.

**Closed** 2022-11-30 07:24 UTC
Labels: bug
