### ISSUE TITLE
Support Face Card Priority

### ISSUE THREAD

**Issue by Ichimoeno** [Fate-Grand-Automata/FGA#1650] opened 2023-08-03 04:15 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2113

### Describe the bug

The servant, Vlad is a support and will not be selected regardless of priority, because the cards go unrecognized. The buffs I think cover up what FGA recognizes as the support card, is there any fix for this or do I have to find an alternative? :0
I wasn't sure if this was a reoccurring issue or if it can be handled, just wondering, thank you!!

### Video

https://youtu.be/2PFXTG4xJ8M 

### Device model

BlueStacks

### Android version

7

**Comment by reconman** [comment] 2023-08-03 17:12
Duplicate of #1076

**Closed by reconman** 2023-08-03 17:12 UTC
Labels: bug
