### ISSUE TITLE
Commands not executing correctly when there are more than 3 enemies per wave?

### ISSUE THREAD

**Issue by darrison** [Fate-Grand-Automata/FGA#687] opened 2021-02-23 22:51 UTC
Is FGA bugged with the CCC event, specifically, with the battles that generates more enemies? 

The issue: I would enter my commands, (h,#,c4,#,eig25) and essentially my goal is to facetank battle 1, np battle 2 and facetank the rest, np battle 3 and facetank the rest. The problem is the script is executing battle 2 commands on battle 1, wave 2.

Am I dumb and messed up somewhere or is this a bug? Dont see anyone talking about this.

I can provide more detail if needed.

**Comment by reconman** [comment] 2021-02-24 10:17
Duplicate of #462

It's either that the background moves or that you have to adjust the stage counter similarity setting.

**Closed by reconman** 2021-02-24 10:17 UTC
Labels: question

**Comment by darrison** [comment] 2021-02-24 14:20
Ah I see what you mean. Yea the background moves and even at 100% it doesnt work. Thanks for the help.

**Comment by reconman** [comment] 2021-02-24 15:07
100 % only leads to the error happening in any quest, since the `Stage 1/3` part of the screen must be 100 % the same without any pixel of difference.

Reducing it might help.
