### ISSUE TITLE
Doesnt 'press' screen on MuMu

### ISSUE THREAD

**Issue by RedMorpho** [Fate-Grand-Automata/FGA#1541] opened 2023-02-22 13:04 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1938

### Describe the bug

It doesn't seem to 'press' the screen on MuMu Player X (Beta) It's ok if its just a problem with the emulator I just kinda like using Mumu.

### Video

https://youtu.be/F9Fvhr3lJUI

### Device model

MuMu Player X V12.1.7.0

### Android version

12

### Screen size

1600x900

### RAM

3

**Comment by reconman** [comment] 2023-02-26 22:27
Duplicate of #1283

**Closed by reconman** 2023-02-26 22:27 UTC
Labels: bug

**Comment by darkxl2** [comment] 2024-04-18 17:52
so fga dont work on mumu?
