### ISSUE TITLE
FGO displays with black bars, but phone has no option to force fullscreen

### ISSUE THREAD

**Issue by ToastCrust** [Fate-Grand-Automata/FGA#845] opened 2021-08-30 22:36 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1483

### Describe the bug

Usually an emulator user, but got an Xperia One III and figured I may as well test on it. The phone is a long 21:9 resolution, and like some others displays with black bars. Unlike Samsung or Huawei, it seems Xperia provides no option for forcing full screen. I've searched "full screen", "full-screen", "fullscreen" in settings, and searched their "game enhancer" for something similar, but it seems Sony just didn't provide any such function.

I figured it was worth having an issue up for phones with the black bar issue but have no workaround.

The phone is notchless, and here's how FGO looks with 3 button navigation. Don't know why it insists on having it uncentered. Gesture navigation will center it, but then have the problematic other black bar.

### Video

https://streamable.com/778voq
https://streamable.com/lzgzj4

### Device model

Xperia One III

### Android version

11

### Screen size

3840x1644

### RAM

12GB

**Comment by itscakebuffet** [comment] 2021-09-10 02:03
Wanted to comment here that this is duplicate of #269 which was supposed to be addressed by #571.  When that was marked as resolved I assumed that  meant 21:9 support would be filed under "won't fix".  #825 mentions an enhancement for a screen detection script but no idea if that's under consideration or doable.  

Don't know if you have tried this @ToastCrust but if you flip the screen the other way around you can get some basic functionality out of the app.  Command card selection works and NP selection is hit or miss along with skills.  Post-battle elements like running the mission again/support selection don't function and you need manual input there.  Obviously not ideal but is sufficient for some farming needs.

**Comment by MathewSachin** [comment] 2021-09-10 12:12
![image](https://user-images.githubusercontent.com/10654537/132850617-8c9c8aef-03c9-46f6-b2d0-bcb9731ca9f9.png)

> I assumed that meant 21:9 support would be filed under "won't fix"

@itscakebuffet  To be clear, 21:9 phones are supported, if they look like this. This screenshot is from a 21:9 device. I assumed Xperia phones would behave the same as any other phone...

I'd already tried doing #825 like a year ago, dropped halfway due to how much effort it needed. I personally won't be doing it unless it becomes an issue for me too 😅.
Rather, it would be much easier to edit the regions in code and use a custom build.

**Comment by itscakebuffet** [comment] 2021-09-11 00:02
@MathewSachin my apologies did not realize 21:9 was supported.  Bummer that Xperia phones exhibit this odd behavior and from what I've been reading it's not exclusive to FGO 🤷‍♂️ .

> Rather, it would be much easier to edit the regions in code and use a custom build.

Haven't done any Kotlin dev work yet but happy to jump in and make a fork explicitly for this use case.  Care to point me in the right direction in the codebase as to where this is defined?  I know screen detection was overhauled at some point so not sure what would be a decent starting point?  Cheers

**Comment by MathewSachin** [comment] 2021-09-11 06:36
https://github.com/Fate-Grand-Automata/FGA/blob/a24df96605198acf566f9eb63e8b509483c003d9/app/src/main/java/com/mathewsachin/fategrandautomata/util/CutoutManager.kt#L107

Just editing the `w` (width) here to only be as wide as FGO should work for your case (including blue bars too if for NA).
Also, if this width is the same for all 21:9 Xperia phones, I suppose I could add it as a special case in the app.

**Comment by itscakebuffet** [comment] 2021-09-11 14:25
Awesome I'll give this a try once I can my dev setup together later this week and let you know.  Thanks again

**Comment by itscakebuffet** [comment] 2021-09-11 21:20
Well turns out I had some time to get this going today and the results don't exactly inspire confidence.  I was able to identify a couple of rough measurements for the black bars.  The top bar matches up to the size of the status bar, which for me is reported as 61px from dumpsys but ends up as 24 in reality.  The bottom bar is taking the size of the navigation bar (144px@ xxhdpi) and also adding the status bar on top of that.  So with a width offset of 192-194 I'm now able to get card selection, skills, and all NP selection, although skill selection seems iffy every now and then (just randomly skips a skill or attempts to use already spent skills).  I have not tested Mystic Code skills though.

Unfortunately post battle actions are still not working and neither is support selection.  Doesn't seem like the offset scales appropriately in those settings so not sure if there's an effective "hack" here.

Skill selection being skipped: https://streamable.com/3hdhfu
Post battle status: https://streamable.com/m77umw

**Comment by MathewSachin** [comment] 2021-09-12 03:12
I can see from the debug mode rectangles that the regions you set are not at exact right places.

Take a screenshot, put in Photoshop/Paint, measure the exact width of FGO, use those values in code. This should be much more reliable.

**Comment by itscakebuffet** [comment] 2021-09-12 05:02
Yep had tried that initially but actually ends up behaving like the stock app weirdly enough.  Exact measurements are 63, 2268, 189 for the top bar, FGO, and bottom bar respectively:

![image](https://user-images.githubusercontent.com/69862970/132972772-456fd8b4-ea4f-4e43-8029-3757d39d6e1a.png)

So setting width to 2268 gets you this:

https://streamable.com/im0s5r

Might try hard coding the other cutout values just to see if there's any change.

**Comment by MathewSachin** [comment] 2021-09-12 06:20
Does your phone have a notch or not? it's not very clear to me from googling. Up to this point, my suggestion of only changing the width assumed that the small black area on the left was due to notch.
If that's not the case, you should try:

```kt
 return Region(63, t, 2268, h) 
```

**Comment by itscakebuffet** [comment] 2021-09-12 14:25
Ah no Xperia devices are notchless so that explains it.  Yes adding the additional 63 offset works great thank you.  So I guess now my question is if all Xperia devices impacted by this have the same 2.5/90/7.5 ratio?  Unfortunately I don't have a device to test on.  @ToastCrust not sure if you're able to generate a build but if the percentages are the same I'd expect the offsets to be 96 and 3456?  If not I can dump an apk here.  Would be cool if it was a constant among devices.

**Comment by MathewSachin** [comment] 2021-09-12 14:38
> Ah no Xperia devices are notchless

Oh, great that you got it working.
One question: does FGA still work if you rotate your phone to reverse landscape?

> I'd expect the offsets to be 96 and 3456

They should be able to verify this by taking a screenshot and measuring or posting a screenshot here and we can take a look.

> not sure if you're able to generate a build

You could use GitHub actions to build FGA like we do. It might take a while to figure out if you're not a programmer, but should be trivial for programmers.

**Comment by itscakebuffet** [comment] 2021-09-12 17:28
> One question: does FGA still work if you rotate your phone to reverse landscape?
Negative the reverse landscape needs the other end of the screen ratio to function.  Seems doable to just add the correct ratio when checking the screen rotation and then return that value as the offset.

>You could use GitHub actions to build FGA like we do
Yeah wasn't sure how deep down this rabbit hole I wanted to go 😅 .  Will look into that next I suppose.

**Comment by reconman** [comment] 2021-09-12 17:36
> Yeah wasn't sure how deep down this rabbit hole I wanted to go 😅 . Will look into that next I suppose.

Enable Actions for your fork and then push to your master branch, then the apk will be built in your repository.

If you're working on branches, a Pull Request to this repository will also lead to a build, but on this repository.

**Comment by itscakebuffet** [comment] 2021-09-12 19:36
@reconman that was indeed painless thank you. @ToastCrust I've generated a build [here](https://github.com/itscakebuffet/FGA/releases) that is a possible fix (works on my Xperia 10).  Mind you this doesn't address the reverse landscape functionality, it just assumes the ratios between the black bars and FGO are consistent across Xperia devices.  Would need some thought about developing a more robust solution.

**Comment by ToastCrust** [comment] 2021-09-13 08:30
Sorry for the slow response. I moved my game back to bluestacks for the current event (these chests are crazy!) so took a sec to find the time to tap out a fresh game on my phone.

Here's a screenshot:
![Screenshot_20210913-003947](https://user-images.githubusercontent.com/11825678/133048313-d9603528-a0a0-4ec6-85ed-48caa543c833.png)

Looking at it, the offsets look like 99 and 3552, assuming I'm not misunderstanding how they're measured? That said, it seems to all be within an acceptable margin of error because...

@itscakebuffet I tried the forked build and it seems to work just great on my phone too. I didn't try any of the more advanced functions like drop counting, but here's a video of it running, picking for a max ascended koyanskaya with s1 lv10, any CE, using Mash's s1 and s2 on t1, and then auto attacking:
https://streamable.com/gsddb9

**Comment by reconman** [comment] 2021-09-13 09:42
@itscakebuffet Other rotation probably works by doing something like this:

```kt
return when(diplay.rotation) {
  Surface.ROTATION_90 -> Region((w * bar_ratio).toInt(), t, (w * fgo_ratio).toInt(), h)
  Surface.ROTATION_270 -> Region((w * fgo_ratio), t, (w * bar_ratio), h)
  else -> Region(l, t, w, h)
}
```

90 degrees is when the home button is on the right, 270 degrees when it's on the left.

You should revert the `import android.view.Surface as Surface1` change and name your variables `fgoRatio` and `barRatio`.

**Comment by itscakebuffet** [comment] 2021-09-14 02:17
> You should revert the import android.view.Surface as Surface1 change and name your variables fgoRatio and barRatio.

@reconman thanks for the help! Changes are complete with support for 270 rotation [here](https://github.com/itscakebuffet/FGA/commit/0def574099f0117db1136b6a0aa73d72d12f5de7).  I ended up needing to add the third ratio to get it working but seems fine.  I am however super bad at math and adjusted the ratios to .026/.9/.074.  Seems slightly more accurate when dealing with skill selection (@ToastCrust you can check the new build if you'd like).

Last thing I'll do here is update my local README to indicate this is intended for Xperia phones only and even then is likely to break as FGO changes.  Not sure what it would take to be able to set these values within the app but if I end up diving more into Kotlin I'll open a PR.  I really appreciate the help @reconman and @MathewSachin 🙏

**Comment by MathewSachin** [comment] 2021-09-18 16:29
@itscakebuffet @ToastCrust can you checks test the apk from this page: https://github.com/Fate-Grand-Automata/FGA/actions/runs/1248908972
I've added a new option: `More options/Advanced/Game Area mode`. Set it to `Xperia` and see if it works.

**Comment by ToastCrust** [comment] 2021-09-19 06:38
@MathewSachin Just tried it with the same scenario I used to test cake's build. It worked in both the default orientation and flipped around upside down. Seems to work great!

**Comment by itscakebuffet** [comment] 2021-09-19 20:56
Confirmed works great for me!

**Closed** 2021-09-21 03:16 UTC
Labels: bug
