### ISSUE TITLE
The game update of Chinese clothes can't be used today

### ISSUE THREAD

**Issue by 1717231** [Fate-Grand-Automata/FGA#1259] opened 2022-07-27 19:27 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1023

### Describe the bug

Select the buddy war interface. It won't move and then the follower's skills can't be released. It may be a problem of game update. I hope the creator can solve this problem early

### Video

...

### Device model

vivoiQOO5

### Android version

12

### Screen size

2376×1080

### RAM

128GB

**Comment by reconman** [comment] 2022-07-27 19:28
Can't help you without a video.

**Comment by reconman** [comment] 2022-07-27 19:40
Duplicate of #1258

**Closed** 2022-07-27 19:40 UTC
Labels: bug
