### ISSUE TITLE
The color card is not recognized 

### ISSUE THREAD

**Issue by Laxwei** [Fate-Grand-Automata/FGA#1081] opened 2022-01-22 18:05 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

1609

### Describe the bug

The color card cannot be recognized normally when the card is selected, only the treasure is recognized 

### Video

https://youtu.be/b80gsNcIVEo

### Device model

LeiDian and Redmi k30s Ultra

### Android version

10

### Screen size

6.67Inch 

### RAM

8GB

**Comment by reconman** [comment] 2022-01-22 18:08
Duplicate of #1064

**Closed by reconman** 2022-01-22 18:08 UTC
Labels: bug
