### ISSUE TITLE
(JP) The app doesn't select any support

### ISSUE THREAD

**Issue by alesardantes** [Fate-Grand-Automata/FGA#808] opened 2021-08-07 07:15 UTC
I have this problem: for some updates after "Nero Fest" the application doesn't select any support, it only searches and refreshes, but the script during the quest works fine. 

However, on the NA server, the app perfectly selects the required support.

Device Model: Moto G7 Power 
App Version: 1446
Android Version: 10 
Screen Size: 1920x1080
RAM: 4G

https://user-images.githubusercontent.com/88400304/128592934-76fc0d80-372e-49e6-bca3-28cf87379576.mp4

**Comment by alesardantes** [comment] 2021-08-07 07:53
In the video, the app should select Artoria but it doesn't. I have even tried with the other supports and the result is the same

**Comment by reconman** [comment] 2021-08-07 07:57
You forgot to enable debug mode in the video.

**Comment by MathewSachin** [comment] 2021-08-07 08:05
@reconman isn't it just another dupe of #796?
We already had so many duplicate issues on this.

**Closed** 2021-08-07 08:08 UTC
Labels: bug, insufficient info

**Comment by reconman** [comment] 2021-08-07 08:15
Think so too
