### ISSUE TITLE
not selecting supports

### ISSUE THREAD

**Issue by Lalex013** [Fate-Grand-Automata/FGA#1479] opened 2022-12-13 13:08 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

Hi, after trying to use fga agian after some time, it didnt choose the support, in battle still works fine. Used to work fine before

![WhatsApp Image 2022-12-13 at 09 37 49](https://user-images.githubusercontent.com/120471025/207325016-c68609d9-49bd-4221-87d4-e2dcae5ac704.jpeg)

### Video

it gets the error in the photo instantly
https://user-images.githubusercontent.com/120471025/207326064-c55e2dfe-52b3-4037-9d01-1ab4ba7ba7f2.mp4

### Device model

huawei nova 9

### Android version

12

### Screen size

2388x1080

### RAM

8

**Comment by reconman** [comment] 2022-12-13 17:54
Duplicate of #1477

**Closed by reconman** 2022-12-13 17:54 UTC
Labels: bug

**Comment by Lalex013** [comment] 2022-12-14 19:13
Thanks! it solved the issue!
