### ISSUE TITLE
Failed to determine type card

### ISSUE THREAD

**Issue by Shadd1** [Fate-Grand-Automata/FGA#1020] opened 2021-12-17 06:02 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1575

### Describe the bug

After NA update with screen, FGA unable to detect the proper card type in battle,
I already try in setting widescreen FGA
I already try active notch
I try differents teams but still failed.

### Video

![Screenshot_20211217-005019_FGA (CI)](https://user-images.githubusercontent.com/29738930/146496322-3c8b1889-61c1-4050-8b1c-ad63699fad58.jpg)
![Screenshot_20211217-005009_FGA (CI)](https://user-images.githubusercontent.com/29738930/146496325-1408079c-ab22-4b57-88cf-c9c754f620ea.jpg)
![Screenshot_20211217-001409_FateGO](https://user-images.githubusercontent.com/29738930/146496327-77df29e9-bf51-4aec-9c2f-c5b12a72a4df.jpg)
https://linksharing.samsungcloud.com/y1MwIKOqVYco

### Device model

Samsung A70

### Android version

11

### RAM

6 GB

**Comment by reconman** [comment] 2021-12-17 06:30
Duplicate of #920

**Closed by reconman** 2021-12-17 06:30 UTC
Labels: bug
