### ISSUE TITLE
3rd wave script error

### ISSUE THREAD

**Issue by yunamon** [Fate-Grand-Automata/FGA#709] opened 2021-04-28 21:25 UTC
I don't see any closed or open topics similar to what I experienced here. Please do  correct me if there is.

Always on the start of the 3rd wave, I noticed that FGA tends to double/multi click on the danger enemy (I had auto target danger enemy turned on) which resulted in it opening the enemy's status box, which in turn blocks the access to skill button presses and such thus stopping the rest of the script. 

Anyway to stop it from happening so it won't affect the flow of the script?

Note: Turning the auto target off works fine so currently I had it off. But auto target is such a good function so it will be sad to had it off on certain farming line up.

**Comment by reconman** [comment] 2021-04-29 14:31
Normally it should always click in the top right to close such windows. I can check the code later to see if I can find anything amiss.

**Comment by MathewSachin** [comment] 2021-05-12 15:42
I couldn't reproduce this. Auto-targeting seems to be working fine. Can you provide a video with Debug mode ON displaying it failing?

**Comment by yunamon** [comment] 2021-05-13 06:46
It seems it happens only during last event, which is the Waltz event. Works ok on daily and farming nodes but the auto target doesnt seem to work even if I turn it on. 

Saw a recent bug post that seems to have the same issue as mine in the latest reply. Maybe you can combine my post with that "script not detecting" post?

**Comment by MathewSachin** [comment] 2021-11-06 10:05
I had adjusted the click location for closing dialogs recently. That should've fixed this.

**Closed by MathewSachin** 2021-11-06 10:05 UTC
Labels: question
