### ISSUE TITLE
CE bomb making script

### ISSUE THREAD

**Issue by Whatwaq** [Fate-Grand-Automata/FGA#665] opened 2021-01-10 13:39 UTC
Before opening an issue:
- [yes ] No one has asked for this feature before in other issues (even the closed ones)
This script would, after the CE spirit orgin list is full, use 1/2 and optionally 3 star ces to enhance a single ces

Inside the enhance-craft essence menu, FGA would scan all the craft essences for a match of the one to be enhanced, so using the support image maker to capture a image of the ce would be needed. 

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Comment by MathewSachin** [comment] 2021-01-10 14:49
Duplicate of #550.
I personally would never make this, so closing.

**Closed by MathewSachin** 2021-01-10 14:49 UTC
Labels: enhancement, wontfix
