### ISSUE TITLE
Present Box ember collection not working as intended (JP)

### ISSUE THREAD

**Issue by AsdAsdAsd001** [Fate-Grand-Automata/FGA#1143] opened 2022-04-03 06:19 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1664

### Describe the bug

FGO JP added x100 spin for lottery, this means ember sizes in the present boxes can go up to 15+. Though max ember size is set as 4, FGA reads 11, 12, 13 and 14 ember sizes as 1, 2, 3, 4, causing it to try and collect those embers.

### Video

[YouTube Video](https://youtu.be/76-MRK_OuZY) 

### Device model

Oppo Reno Z

### Android version

11

**Comment by reconman** [comment] 2022-04-03 06:32
Duplicate of #1009

**Closed** 2022-04-03 06:32 UTC
Labels: bug
