### ISSUE TITLE
Unable to Start Quest 

### ISSUE THREAD

**Issue by Valkdoorr** [Fate-Grand-Automata/FGA#1157] opened 2022-04-23 02:20 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

When I try to launch a mission using the script, it will tap start quest but the mission will not start. If I proceed to stop the script and try to manually start the mission I am unable to interact with the game at all.

### Video

I tried for over an hour to get a recording to work but I cannot get it take take video and run the script at the same time no matter what settings I adjust.

### Device model

S22 Ultra

### Android version

12

**Comment by reconman** [comment] 2022-04-26 19:49
Duplicate of #1100

**Closed by reconman** 2022-04-26 19:49 UTC
Labels: bug
