### ISSUE TITLE
FGA chooses wrong skill targets occasionally

### ISSUE THREAD

**Issue by Werror23** [Fate-Grand-Automata/FGA#1458] opened 2022-11-23 17:05 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

1892

### Describe the bug

FGA starts to choose wrong skill targets from time to time. It can work without issues for a couple of runs, then it chooses a second servant as a skill target instead of first/third one. Everything else works ok.

Additional info:
I used FGA before on the same phone, but with MIUI(miui 12, android 10) installed. Had no problems. A couple of day before I flashed new ROM (lineageos 19.1, android 12) and immediately experienced this issue. Although the FGA version was different. So maybe new ROM has nothing to do with thus issue

### Video

FGA still conflicts with video recording for me for some reason. It also happened on miui.
![Screenshot_20221123-182609_Fate_GO](https://user-images.githubusercontent.com/15365283/203606556-b3a084cb-f49d-4f2e-b993-37cfd0740b8b.png)

### Device model

Xiaomi Mi Mix 3

### Android version

12

### Screen size

2340x1080

### RAM

6

**Comment by reconman** [comment] 2022-11-23 21:22
Duplicate of #1452 #1450

**Closed** 2022-11-23 21:22 UTC
Labels: bug

**Comment by Werror23** [comment] 2022-11-24 14:57
> Duplicate of #1452

It's a bit different. I'll try to explain it better. FGA doesn't miss taps. It also choses correct skills in correct order. It instead makes wrong taps in servant selection window. It can work correctly for some time(although it's not guaranteed, sometime it brokes even in the first battle). But then it will start choosing the second servant(instead of first or third one) as a target of those skills. It just presses in the middle of the second servant's portrait in the selection window. (I "fixed" it by placing my dd in the second slot, it looks like it "works" now. But I haven't used it as much, not sure if it won't break in some other way)

I tried to put "t1" in the command line, like you proposed in 1452, but it doesn't work. 

Unfortunately can't provide a video. I will try to capture it using PC through debug mode, but it wasn't compatible with working fga either. So I don't have a lot of expectations.
