### ISSUE TITLE
The latest update completely broke the app, it doesn't work nor open anymore. 

### ISSUE THREAD

**Issue by Zushikina-kun** [Fate-Grand-Automata/FGA#1825] opened 2024-05-25 00:58 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

2687

### Describe the bug

The latest Update completely broke the app, it doesn't work nor open anymore, it just keeps crashing and exiting the time I open it in that same instant. 

https://github.com/Fate-Grand-Automata/FGA/assets/40606485/dd4e065b-278f-477c-9b7d-269f0ab083a5

### Video

Device: Xiaomi Poco F3 
SoC: Snapdragon 870 
Ram: 8gb
Storage: 256gb

![Screenshot_2024-05-25-08-54-17-971_com android settings](https://github.com/Fate-Grand-Automata/FGA/assets/40606485/d3536c97-7f3b-4fdf-b6c6-da633b80e1a7)

### Device model

Xiaomi Poco F3

### Android version

13

### Screen size

1080x2400

### RAM

8GB

**Comment by vybze** [comment] 2024-05-25 01:06
Duplicate of #1824

**Closed by vybze** 2024-05-25 01:06 UTC
Labels: bug
