### ISSUE TITLE
Unable to proceed if 2 servants level up their bonds at the same time

### ISSUE THREAD

**Issue by metapone** [Fate-Grand-Automata/FGA#1522] opened 2023-01-15 17:21 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1871

### Describe the bug

After a battle, when the first servant's Bond Level Up screen appears, FGA will click to skip it. If another Bond Level Up screen appears next, FGA will hang.

### Video

Ran out of new servants to test, so I'm unable to get 2 servants to level up at the same time to reproduce.

### Device model

Xiaomi Redmi 5 Plus

### Android version

11

### Screen size

1080x2160

### RAM

4GB

**Comment by reconman** [comment] 2023-02-17 19:14
I won't fix this since it's hard to reproduce and not many users will encounter it.

**Closed by reconman** 2023-02-17 19:14 UTC
Labels: bug
