### ISSUE TITLE
Need help with a servant priority problem

### ISSUE THREAD

**Issue by FGAhelpneeded** [Fate-Grand-Automata/FGA#1370] opened 2022-09-03 16:03 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

I am having an issue with servant priority. Not sure if this should have gone under reporting problems or if it simply something I am missing. I have a setup where servant 3 is a support. Wave one servant priority is 123 and works. Wave 2 uses Arash NP and priority is 123. Arash is in slot 1 and I do this because I know Arash will clear the wave with the NP and I want to save cards, especially for the support servant.

The problem is wave 3. The priority for wave 3 is 324561 but it seems to prioritize the support servant last. I haven't been able to figure out how to fix this. It is not prioritizing weakness as the support is the only one with an advantage. 

Appreciate any input that can be provided. Screenshots of the priority settings are attached. I have a video of it running but it is too big. Its been awhile since I have used a service to upload a video and create a link so tips on that will be appreciated if anyone wants to see what it is doing. 

I have other ways I could reliably clear it without face cards but I am trying to run event CE's and use extra slots for getting bond experience for low level servants. It not prioritizing the support servants face cards on wave 3 puts the run at risk of failing. 

Thank you. 

<img height="400px" src="https://user-images.githubusercontent.com/112764478/188275399-a4633a33-2c4a-4350-b817-780682b4565f.jpg" />
<img height="400px" src="https://user-images.githubusercontent.com/112764478/188275425-ebdc2943-ad41-4612-a772-146a8d3f9b26.jpg" />
<img height="400px" src="https://user-images.githubusercontent.com/112764478/188275439-1e5092d3-5124-4b7d-baac-02bc7b36325a.jpg" />

https://youtu.be/G8kzPsWRcdc

**Comment by reconman** [comment] 2022-09-03 16:04
I need a video too

**Comment by FGAhelpneeded** [comment] 2022-09-03 17:35
Link added to the bottom of the original post.

**Comment by ArthurKun021** [comment] 2022-09-14 23:17
different case, but same issue with the priority

Like the post above wave 1 and wave 2 is normal

the positioning of my servants is 

Servant 1 ---Servant 2---Support Servant

the priority I set for wave 3 is the normal 123. During the first turn of wave 3, the priority works as intended but after that it gets jumble up. During the succeeding turns in wave 3, the one that I did set as the highest priority(which is 1/servant 1) turn into lowest priority

**Comment by reconman** [comment] 2022-09-27 21:39
I forgot about this issue, found the reason:
![image](https://user-images.githubusercontent.com/12360257/192640601-46a6b246-3493-4c03-9d63-b1e172ad4927.png)

Duplicate of #1076

**Closed by reconman** 2022-09-27 21:39 UTC
Labels: question
