### ISSUE TITLE
Allow ember claiming from gift box to get more than x4 stacks

### ISSUE THREAD

**Issue by enshael** [Fate-Grand-Automata/FGA#1125] opened 2022-03-05 07:32 UTC
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

With the 100x roll introduced in JP last Christmas 2021, there's higher chances of getting more than x4 stacks of embers in the inbox. 

Is it possible to make it match with any variable number? If not, at least up to x10 would be good enough. I assume it will conflict with x1 if using images, so maybe just x9?

**Comment by reconman** [comment] 2022-03-05 08:16
Duplicate of #1009

**Comment by reconman** [comment] 2022-03-05 08:18
FGA currently can't read font and has to rely on image detection. That's why we can't deal with this case easily.

**Closed by reconman** 2022-03-05 08:18 UTC
Labels: enhancement
