### ISSUE TITLE
The latest update broke everything

### ISSUE THREAD

**Issue by brightEcho** [Fate-Grand-Automata/FGA#949] opened 2021-11-16 08:51 UTC
### Preparation

- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] My question isn't answered in any other issues (even the closed ones)

### Your question

Tried doing my daily ember runs after the latest NA update, and the app just doesn't work anymore. Most probably has something to do with the forced widescreen they added in.

**Comment by Stundedx** [comment] 2021-11-16 09:38
Just force the app to recognize it as JP, then everything will work fine.
![image](https://user-images.githubusercontent.com/33225465/141960307-5f383885-1f14-4d02-a3f4-d9149d35e8ee.png)

**Comment by reconman** [comment] 2021-11-16 09:39
Duplicate of #948

**Closed by reconman** 2021-11-16 09:39 UTC
Labels: question
