### ISSUE TITLE
Ember recieve script selects ember stacks above the max ember stack amount

### ISSUE THREAD

**Issue by Tom3kk** [Fate-Grand-Automata/FGA#1487] opened 2022-12-17 19:38 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1908

### Describe the bug

The script selects incorrect stacks of embers, as if it was not looking at the entire number 

### Video

[bruhtube video of the issue](https://youtu.be/I5E6_JBWcIA)

### Device model

Bluestacks 5.5.100.1040 N32

### Android version

7

**Comment by reconman** [comment] 2022-12-18 21:18
Duplicate of #1009 

I can't think of any solution other than using OCR to parse the text.

**Closed by reconman** 2022-12-18 21:18 UTC
Labels: bug

**Comment by CDB-Man** [comment] 2022-12-25 19:33
If the only solution is image matching, then my vote is having available the single digits 1-9 would probably (?) be sufficient.
