### ISSUE TITLE
Friend request script stop on screen

### ISSUE THREAD

**Issue by randoomdude** [Fate-Grand-Automata/FGA#978] opened 2021-11-23 20:31 UTC
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

So right now, if you run the script to only go through a quest once, it will stop right after where you could normally accept a friend request, stopping right after on the quest select screen itself. I know the friend request is still broken since last year, but at the very least could you make an option to toggle the script stop at this screen instead of right after it, at least for single runs?

**Comment by reconman** [comment] 2021-11-23 20:39
> I know the friend request is still broken since last year

It's currently working as intended.

**Comment by reconman** [comment] 2021-11-23 20:39
Duplicate of #977

**Closed by reconman** 2021-11-23 20:39 UTC
Labels: enhancement

**Comment by randoomdude** [comment] 2021-11-23 23:15
> 

It always skips the screen though? I was reading about the feature from the 2020 threads and apparently there was an option to check friend request before the support section, but it's not there anymore?
![image](https://user-images.githubusercontent.com/6027132/143143568-9cb227e5-22af-4b64-8378-bd7e2d441407.png)
hough?

**Comment by reconman** [comment] 2021-11-23 23:18
No, you're misunderstanding it. There was a bug that FGA was stuck on the friend screen because of UI changes in FGO.

Since the fix, it skips the friend request again as intended.

**Comment by randoomdude** [comment] 2021-11-23 23:22
I see, it's just that after a fight is ended, I'll look at the screen and scramble to click friend request on someone I really wanted to add, but then it exits out before I can reach it, stopping right after, so I figure if it stops anyway to just stop on the screen before so I can click friend request without rushing to hit it in time

**Comment by reconman** [comment] 2021-11-23 23:27
The automatic friend request feature would be better for doing multiple runs in a row. (optionally with apples)

Who wants to click a button after every run?

**Comment by randoomdude** [comment] 2021-11-24 02:17
yeah ideally it would be automated, but if you're only doing one run anyway I think it can also work fine, so you can look over the person's servant/ce and see if you want to add them, and you're only doing it so many times until you have a satisfactory amount of friends, I think it would work as a half measure until something more complex is implemented
