### ISSUE TITLE
I press start and nothing happens.

### ISSUE THREAD

**Issue by RaimeiAzure** [Fate-Grand-Automata/FGA#1248] opened 2022-07-14 06:36 UTC
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1721

### Describe the bug

When I open FGO, in the support selection list I put to start FGA and nothing happens. Not only on the support list, but on any other screen in the game.  Just nothing happens.

### Video

https://youtu.be/uxuNey_w8hw

### Device model

Xiaomi Redmi note 8 Pro 

### Android version

10

### Screen size

2340x1080

### RAM

6GB

**Comment by reconman** [comment] 2022-07-14 06:46
Duplicate of #1230

**Closed** 2022-07-14 06:46 UTC
Labels: bug

**Comment by RaimeiAzure** [comment] 2022-07-14 07:10
> Duplicate of #1230

The problem was solved. Thank you!
