### ISSUE TITLE
No Script Mode available [Bluestacks]

### ISSUE THREAD

**Issue by Akryos** [Fate-Grand-Automata/FGA#766] opened 2021-07-05 16:22 UTC
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
I installed the current version of FGA (canary-1389) on Bluestacks (v4.260.0.1032, 32-bit Android, Graphics Engine in Compatibility mode).

I intended to use the app for FP Gacha, but instead of **Script Mode**, the only thing I can choose is Battle Configs. The menu generally seems a bit different to the version in reconmans video.

**Screenshots**
This is the main menu I see when opening the app:
![grafik](https://user-images.githubusercontent.com/11232806/124498316-6e5b4f00-ddbc-11eb-950d-3f061f214488.png)

**Video**
No video attached.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S8 Plus
 - Screen size: Resolution 1600x900
 - Android Version: Android 7.1.2 (according to demo.mobiledetect.net)
 - RAM: 4GB

**Comment by reconman** [comment] 2021-07-05 16:24
Duplicate of #765

**Closed by reconman** 2021-07-05 16:24 UTC
Labels: bug
